name = "fauxid"
compatibility_date = "2023-12-01"
workers_dev = true
main = "_worker.js"

[build]
command = "CLOUDFLARE=true next build"
cwd = "."
watch_dir = "app"

[env.production]
route = ""
zone_id = ""

[site]
bucket = ".next/static"

# 移除了过时的entry-point和build.upload配置 
